In [1]:
# 1 import libraries
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#  2 Load Dataset
df = pd.read_csv("/content/drive/MyDrive/yuva_intern/E-Commerce_Order_Fulfillment_Dataset.csv")

In [4]:
# 3 Check Dataset Shape
df.shape

(50000, 10)

In [5]:
# 4 Display First records
df.head()

,Order_ID,Customer_Region,Product_Category,Order_Date,Ship_Date,Delivery_Date,Shipping_Mode,Shipping_Cost,Delivery_Status,Delivery_Days
0,OR10000,West,Home,5/12/2024,5/16/2024,5/26/2024,Standard,122,Delivered,10
1,OR10001,Central,Home,4/19/2025,4/24/2025,4/26/2025,Standard,143,Delivered,2
2,OR10002,East,Home,7/2/2025,7/4/2025,7/11/2025,Standard,107,Delayed,7
3,OR10003,Central,Grocery,10/4/2025,10/8/2025,10/16/2025,Standard,145,Delayed,8
4,OR10004,Central,Sports,10/31/2023,11/2/2023,11/7/2023,Standard,121,Delivered,5

In [6]:
#  5 Check Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          50000 non-null  object
 1   Customer_Region   50000 non-null  object
 2   Product_Category  50000 non-null  object
 3   Order_Date        50000 non-null  object
 4   Ship_Date         50000 non-null  object
 5   Delivery_Date     50000 non-null  object
 6   Shipping_Mode     50000 non-null  object
 7   Shipping_Cost     50000 non-null  int64
 8   Delivery_Status   50000 non-null  object
 9   Delivery_Days     50000 non-null  int64
dtypes: int64(2), object(8)
memory usage: 3.8+ MB

In [7]:
# 6 Descriptive statistics
df.describe()

       Shipping_Cost  Delivery_Days
count   50000.000000   50000.000000
mean      138.838280       5.989760
std        72.498689       2.573649
min        50.000000       2.000000
25%        88.000000       4.000000
50%       121.000000       6.000000
75%       164.000000       8.000000
max       399.000000      10.000000

In [8]:
# 7 Categorical Summary
df.describe(include='object')

,Order_ID,Customer_Region,Product_Category,Order_Date,Ship_Date,Delivery_Date,Shipping_Mode,Delivery_Status
count,50000,50000,50000,50000,50000,50000,50000,50000
unique,50000,5,6,1461,1466,1473,3,3
top,OR59983,Central,Sports,7/27/2024,3/19/2022,10/30/2022,Standard,Delivered
freq,1,10117,8380,52,54,57,29973,40062

In [9]:
# 8 Check Missing values
missing_values = df.isnull().sum()
missing_values

Order_ID            0
Customer_Region     0
Product_Category    0
Order_Date          0
Ship_Date           0
Delivery_Date       0
Shipping_Mode       0
Shipping_Cost       0
Delivery_Status     0
Delivery_Days       0
dtype: int64

In [10]:
#  9 Calculate missing value %age
missing_percentage = missing_values / len(df) *100
missing_percentage

Order_ID            0.0
Customer_Region     0.0
Product_Category    0.0
Order_Date          0.0
Ship_Date           0.0
Delivery_Date       0.0
Shipping_Mode       0.0
Shipping_Cost       0.0
Delivery_Status     0.0
Delivery_Days       0.0
dtype: float64

In [11]:
# 10 Check Duplicate check
df.duplicated().sum()

np.int64(0)

In [12]:
# 11 Unique categorical values
Customer_Regions = df['Customer_Region'].unique()
Customer_Regions

array(['West', 'Central', 'East', 'South', 'North'], dtype=object)

In [13]:
# 12 Unique Product Categories :
Product_categories = df['Product_Category'].unique()
print(Product_categories)

['Home' 'Grocery' 'Sports' 'Fashion' 'Beauty' 'Electronics']

In [14]:
# 13 Unique Shipping Modes :
Shipping_modes = df['Shipping_Mode'].unique()
print(Shipping_modes)

['Standard' 'Express' 'Same Day']

In [15]:
# 14 Unique Delivery Status:
Delivery_status = df['Delivery_Status'].unique()
print(Delivery_status)

['Delivered' 'Delayed' 'Returned']

In [16]:
#  15 Delivery status count
delivery_status_counts = df['Delivery_Status'].value_counts()
delivery_status_counts

Delivery_Status
Delivered    40062
Delayed       7505
Returned      2433
Name: count, dtype: int64

In [17]:
# 16 Delivery Status Percentage Result
delivery_status_percentage = df['Delivery_Status'].value_counts(normalize=True) * 100
delivery_status_percentage

Delivery_Status
Delivered    80.124
Delayed      15.010
Returned      4.866
Name: proportion, dtype: float64

In [18]:
date_columns = ['Order_Date', 'Ship_Date', 'Delivery_Date']

for col in date_columns:
    df[col] = pd.to_datetime(df[col])

In [19]:
# Add new colums "Order_to_Ship_Days", "Order_to_Delivery_Days"

df['Order_to_Ship_Days'] = (df['Ship_Date'] - df['Order_Date']).dt.days
df['Order_to_Delivery_Days'] = (df['Delivery_Date'] - df['Order_Date']).dt.days

In [20]:
# Check dataset shape after adding new columns :
df.shape

(50000, 12)

# KPIs

In [21]:
# Order Fulfillment Cycle Time

Order_to_Delivery_Days = df['Order_to_Delivery_Days'].mean()

print("Average Order to Delivery Days:", round(Order_to_Delivery_Days, 2))

Average Order to Delivery Days: 8.48

In [22]:
# KPI 2: Ship Processing Time

Order_to_Ship_Days = df['Order_to_Ship_Days'].mean()
print("Average Order to Ship Days:", round(Order_to_Ship_Days,2))

Average Order to Ship Days: 2.49

In [23]:
# KPI 3: Delivery Delay Rate

delay_count = (df['Delivery_Status'] == 'Delayed').sum()

delay_rate = (delay_count / len(df)) * 100

print("Delayed Orders:", delay_count)
print("Delivery Delay Rate:", round(delay_rate, 2), "%")

Delayed Orders: 7505
Delivery Delay Rate: 15.01 %

In [24]:
# KPI 4: Return Rate

return_rate = (df['Delivery_Status'] == 'Returned').mean() * 100

print("Return Rate:", round(return_rate, 2), "%")

Return Rate: 4.87 %

In [25]:
# KPI 5: Delivery Success Rate

delivery_sucess_rate = (df['Delivery_Status'] == 'Delivered').sum() / len(df) * 100

print("Delivery Success Rate:", round(delivery_sucess_rate, 2), "%")

Delivery Success Rate: 80.12 %

In [26]:
# KPI 6: Average Shipping Cost

average_shipping_cost = df['Shipping_Cost'].mean()

print("Average Shipping Cost:", round(average_shipping_cost, 2))

Average Shipping Cost: 138.84

In [27]:
# KPI 7: Shipping Cost by Mode

cost_by_mode = df.groupby('Shipping_Mode')['Shipping_Cost'].mean()

print("Shipping Cost by Mode:",round(cost_by_mode,2))

Shipping Cost by Mode: Shipping_Mode
Express     164.58
Same Day    299.59
Standard     99.29
Name: Shipping_Cost, dtype: float64